package models

type InterfaceDef struct {
	Id                  int
	IsIf3               bool
	Type                int
	ContentType         int
	OriginalX           int
	OriginalY           int
	OriginalWidth       int
	OriginalHeight      int
	WidthMode           byte
	HeightMode          byte
	XPositionMode       byte
	YPositionMode       byte
	ParentId            int
	IsHidden            bool
	ScrollWidth         int
	ScrollHeight        int
	NoClickThrough      bool
	SpriteId            int
	TextureId           int
	SpriteTiling        bool
	Opacity             byte
	BorderType          byte
	ShadowColor         int
	FlippedVertically   bool
	FlippedHorizontally bool
	ModelType           int
	ModelId             int
	OffsetX2d           int
	OffsetY2d           int
	RotationX           int
	RotationY           int
	RotationZ           int
	ModelZoom           int
	Animation           int
	Orthogonal          bool
	ModelHeightOverride int
	ModelWidthOverride  int // unknown - runelite ignores this
	FontId              int
	Text                string
	LineHeight          byte
	XTextAlignment      byte
	YTextAlignment      byte
	TextShadowed        bool
	TextColor           int
	Filled              bool
	LineWidth           byte
	LineDirection       bool
	ClickMask           int
	Name                string
	Actions             []string
	DragDeadZone        byte
	DragDeadTime        byte
	DragRenderBehavior  bool
	TargetVerb          string
}
